In [14]:
from osgeo import gdal
import numpy as np
pixels = 436*506

In [16]:
extract_band = 1
image = np.zeros([pixels, 4], dtype=np.uint8)
gdal.GetDriverByName('EHdr').Register()
img = gdal.Open('subfebformosat2')
while 4 >= extract_band:
    bandx = img.GetRasterBand(extract_band)
    datax = bandx.ReadAsArray()
    temp = datax
    store = temp.reshape(pixels)
    for i in range(pixels):
        image[i][extract_band - 1] = store[i]
    extract_band = extract_band + 1

print(image)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 ..., 
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
